import type { MileageEntry, MileageUnit } from '../types';
import { formatDate, formatPrice } from './formatters';

/**
 * Export entries to CSV format
 */
export function exportToCSV(entries: MileageEntry[], unit: MileageUnit): void {
  // Sort by date descending
  const sortedEntries = [...entries].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );

  // CSV headers
  const headers = [
    'Date',
    'Miles',
    'Liters',
    'Price (pence/L)',
    'Total Cost (£)',
    unit === 'km/l' ? 'Mileage (km/L)' : 'Mileage (mpg)',
  ];

  // CSV rows
  const rows = sortedEntries.map(entry => [
    entry.date,
    entry.miles.toFixed(1),
    entry.liters.toFixed(2),
    entry.pricePence.toFixed(1),
    ((entry.pricePence * entry.liters) / 100).toFixed(2),
    unit === 'km/l' 
      ? entry.mileageKmPerL.toFixed(2) 
      : entry.mileageMilesPerGallon.toFixed(2),
  ]);

  // Combine headers and rows
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');

  // Create and download file
  downloadFile(csvContent, 'mileage-data.csv', 'text/csv');
}

/**
 * Export entries to PDF format (simple HTML-based PDF)
 */
export function exportToPDF(entries: MileageEntry[], unit: MileageUnit): void {
  // Sort by date descending
  const sortedEntries = [...entries].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );

  // Calculate summary stats
  const totalMiles = entries.reduce((sum, e) => sum + e.miles, 0);
  const totalLiters = entries.reduce((sum, e) => sum + e.liters, 0);
  const totalCost = entries.reduce((sum, e) => sum + (e.pricePence * e.liters), 0);
  const avgMileage = unit === 'km/l'
    ? entries.reduce((sum, e) => sum + e.mileageKmPerL, 0) / entries.length
    : entries.reduce((sum, e) => sum + e.mileageMilesPerGallon, 0) / entries.length;

  // Generate HTML content
  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>Car Mileage Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; color: #333; }
    h1 { color: #3b82f6; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
    .summary { display: flex; gap: 20px; margin: 20px 0; flex-wrap: wrap; }
    .stat { background: #f0f9ff; padding: 15px; border-radius: 8px; min-width: 120px; }
    .stat-label { font-size: 12px; color: #666; }
    .stat-value { font-size: 24px; font-weight: bold; color: #1e40af; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { background: #3b82f6; color: white; padding: 12px; text-align: left; }
    td { padding: 10px; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) { background: #f8fafc; }
    .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>
  <h1>🚗 Car Mileage Report</h1>
  <p>Generated: ${new Date().toLocaleDateString()}</p>
  
  <div class="summary">
    <div class="stat">
      <div class="stat-label">Total Entries</div>
      <div class="stat-value">${entries.length}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Total Miles</div>
      <div class="stat-value">${totalMiles.toFixed(0)}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Total Liters</div>
      <div class="stat-value">${totalLiters.toFixed(1)}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Total Spent</div>
      <div class="stat-value">${formatPrice(totalCost)}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Avg ${unit}</div>
      <div class="stat-value">${avgMileage.toFixed(1)}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Miles</th>
        <th>Liters</th>
        <th>Price (p/L)</th>
        <th>Cost</th>
        <th>${unit}</th>
      </tr>
    </thead>
    <tbody>
      ${sortedEntries.map(entry => `
        <tr>
          <td>${formatDate(entry.date)}</td>
          <td>${entry.miles.toFixed(1)}</td>
          <td>${entry.liters.toFixed(2)}</td>
          <td>${entry.pricePence.toFixed(1)}p</td>
          <td>${formatPrice(entry.pricePence * entry.liters)}</td>
          <td>${(unit === 'km/l' ? entry.mileageKmPerL : entry.mileageMilesPerGallon).toFixed(2)}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="footer">
    <p>Generated by Carmi - Car Mileage Tracker</p>
  </div>
</body>
</html>
  `;

  // Open print dialog
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  }
}

/**
 * Helper to download a file
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

